# Generated by Django 2.1.1 on 2018-11-10 09:50

import articles.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('body', ckeditor.fields.RichTextField(blank=True, db_index=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('desc_for_find', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to=articles.models.generate_filename_jpg, verbose_name='IMG')),
                ('attribution', models.CharField(db_index=True, default=' ', max_length=300, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('desc_for_find', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Добавить комментарий')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
                ('comment_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Category', verbose_name='Категория'),
        ),
    ]
