# Generated by Django 2.1.3 on 2018-12-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='attribution',
        ),
    ]
