# Generated by Django 2.1.1 on 2018-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181019_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Category', verbose_name='Категория'),
        ),
    ]
