# Generated by Django 2.1.2 on 2018-10-19 18:04

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181019_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.generate_filename_jpg, verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
    ]
