# Generated by Django 2.1.2 on 2018-10-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181022_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
