# Generated by Django 2.1.3 on 2018-12-30 16:17

import booklist.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('description', ckeditor.fields.RichTextField(blank=True, db_index=True, verbose_name='Описание')),
                ('desc_for_find', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
                ('lang_category', models.IntegerField(choices=[(1, 'Русский'), (2, 'Английский')], db_index=True, default=1, verbose_name='Язык')),
                ('book_file', models.FileField(blank=True, null=True, upload_to=booklist.models.generate_filename, verbose_name='Файл PDF')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to=booklist.models.generate_filename_jpg, verbose_name='IMG')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc_for_find_cat', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords_cat', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Добавить комментарий')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.Book')),
                ('comment_author_book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='booklist.Category', verbose_name='Категория'),
        ),
    ]
