# Generated by Django 2.1.2 on 2018-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='desc_for_find_cat',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords_cat',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кейвордс'),
        ),
    ]
