# Generated by Django 2.1.2 on 2018-10-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_temporarybanip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
    ]
