# Generated by Django 2.1.2 on 2018-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_delete_temporarybanip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
