# Generated by Django 2.1.3 on 2018-12-30 16:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, verbose_name='Ссылка')),
                ('desc_for_find', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Добавить комментарий')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('description', ckeditor.fields.RichTextField(blank=True, db_index=True, verbose_name='Описание')),
                ('desc_for_find', models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Кейвордс')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to=video.models.generate_filename_jpg, verbose_name='IMG')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(related_name='courses', to='video.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Course'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_author_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
