# Generated by Django 2.1.4 on 2018-12-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img_file',
        ),
    ]
