# Generated by Django 2.1.2 on 2018-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20181019_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc_for_find',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кейвордс'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_for_find',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание для поиска'),
        ),
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кейвордс'),
        ),
    ]
