# Generated by Django 2.1.2 on 2018-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20181022_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
    ]
