# Generated by Django 2.1.2 on 2018-10-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20181022_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='img_file',
            new_name='img_file_link',
        ),
    ]
