# Generated by Django 2.1.2 on 2018-10-22 09:28

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20181022_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img_file_link',
            field=models.ImageField(blank=True, null=True, upload_to=video.models.generate_filename_jpg_video, verbose_name='IMG'),
        ),
    ]
